// @generated by tpt-proto-codegen-rust. DO NOT EDIT.
use tpt_proto_core as __core;
use __core::{Message, Reader, Writer, UnknownFieldSet, WireType};
use __core::scalar;
use __core::packed;
use std::collections::HashMap;

use tpt_proto_grpc as __grpc;
use async_trait::async_trait;
use __grpc::{Channel, ClientStream, ServerStream};

/// Generated from protobuf message `ex.Ping`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ExPing {
    pub msg: String,
    pub unknown_fields: UnknownFieldSet,
}

impl ExPing {
    /// Protobuf full name of this message.
    pub const PROTO_FULL_NAME: &'static str = "ex.Ping";
}

impl Message for ExPing {
    fn encode(&self, w: &mut Writer) -> __core::Result<()> {
        if !self.msg.is_empty() {
            scalar::encode_string(w, 1, &&self.msg);
        }
        self.unknown_fields.encode(w);
        Ok(())
    }

    fn merge_from(&mut self, r: &mut Reader) -> __core::Result<()> {
while !r.is_empty() {
let tag = r.read_tag()?;
match tag.field_number {
1 => {
            self.msg = r.read_string_owned()?;
}
                _ => {
self.unknown_fields.store(tag, r)?;
}
}
}
Ok(())
}
}

/// Builder for [`ExPing`].
pub struct ExPingBuilder {
    inner: ExPing,
}

impl ExPingBuilder {
    /// Create a new builder seeded with default values.
    pub fn new() -> Self {
        Self { inner: ExPing::default() }
    }
    /// Set the `msg` field.
    pub fn msg(mut self, v: String) -> Self {
        self.inner.msg = v;
        self
    }
    /// Build the message, validating required fields.
    pub fn try_build(self) -> Result<ExPing, String> {
        Ok(self.inner)
    }
    /// Build the message without required-field validation.
    pub fn build(self) -> ExPing {
        self.inner
    }
}

/// Generated from protobuf message `ex.Pong`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ExPong {
    pub msg: String,
    pub unknown_fields: UnknownFieldSet,
}

impl ExPong {
    /// Protobuf full name of this message.
    pub const PROTO_FULL_NAME: &'static str = "ex.Pong";
}

impl Message for ExPong {
    fn encode(&self, w: &mut Writer) -> __core::Result<()> {
        if !self.msg.is_empty() {
            scalar::encode_string(w, 1, &&self.msg);
        }
        self.unknown_fields.encode(w);
        Ok(())
    }

    fn merge_from(&mut self, r: &mut Reader) -> __core::Result<()> {
while !r.is_empty() {
let tag = r.read_tag()?;
match tag.field_number {
1 => {
            self.msg = r.read_string_owned()?;
}
                _ => {
self.unknown_fields.store(tag, r)?;
}
}
}
Ok(())
}
}

/// Builder for [`ExPong`].
pub struct ExPongBuilder {
    inner: ExPong,
}

impl ExPongBuilder {
    /// Create a new builder seeded with default values.
    pub fn new() -> Self {
        Self { inner: ExPong::default() }
    }
    /// Set the `msg` field.
    pub fn msg(mut self, v: String) -> Self {
        self.inner.msg = v;
        self
    }
    /// Build the message, validating required fields.
    pub fn try_build(self) -> Result<ExPong, String> {
        Ok(self.inner)
    }
    /// Build the message without required-field validation.
    pub fn build(self) -> ExPong {
        self.inner
    }
}

/// gRPC server trait for `ex.Echo`.
#[async_trait]
#[allow(unused_variables)]
pub trait Echo: Send + Sync {
    /// Handler for `ex.Echo.unary`.
    async fn unary(&self, request: __grpc::Request<Ping>) -> std::result::Result<__grpc::Response<Pong>, __grpc::Status>;
}

/// gRPC client stub for `ex.Echo`.
pub struct EchoClient {
    pub channel: __grpc::Channel,
}

impl EchoClient {
    /// Create a new client stub over the given channel.
    pub fn new(channel: __grpc::Channel) -> Self {
        Self { channel }
    }
    /// Call `ex.Echo.unary`.
    pub async fn unary(&self, request: __grpc::Request<Ping>) -> std::result::Result<__grpc::Response<Pong>, __grpc::Status> {
        let (message, trailers) = self.channel
            .unary::<Ping, Pong>(
                "/ex.Echo/Unary",
                request.context.metadata.clone(),
                &request.message,
            )
            .await?;
        Ok(__grpc::Response::new(message).with_metadata(trailers))
    }
}

