[package]
name = "tpt-proto-text"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Text format printer and parser"

[dependencies]
tpt-proto-descriptor = { workspace = true }
tpt-proto-core = { workspace = true }
tpt-proto-reflect = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tpt-proto-core = { workspace = true }
